#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.


# Install python 2.7, adapted from 
# https://github.com/ehazlett/openshift-diy-py27-django/blob/master/.openshift/action_hooks/pre_build

PY_VERSION='2.7.6'

if [ ! -d $OPENSHIFT_DATA_DIR/bin ]; then
  if [ "$OPENSHIFT_DATA_DIR/bin/python -V" != 'Python $PY_VERSION' ]; then
    # install python
    cd $OPENSHIFT_TMP_DIR
    wget http://python.org/ftp/python/$PY_VERSION/Python-$PY_VERSION.tgz
    tar -zxf Python-$PY_VERSION.tgz
    cd Python-$PY_VERSION
    ./configure --prefix=$OPENSHIFT_DATA_DIR
    make install
  fi

  # set path
  export PATH=$OPENSHIFT_DATA_DIR/bin:$PATH

  # install setuptools and pip
  cd $OPENSHIFT_TMP_DIR
  wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
  wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
  python ez_setup.py
  python get-pip.py
  
  # cleanup
  rm -rf $OPENSHIFT_TMP_DIR/*
fi
